workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.lunarae.mobile

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Clean and reinstall pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
